version: '3.8'

services:
  # Database
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lemonstand
    volumes:
      - mongo_data:/data/db

  # Redis cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # RabbitMQ message broker with management UI
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # management UI

  # Service registry responsible for service discovery and health monitoring
  service-registry:
    build: ./packages/service-registry
    ports:
      - "3006:3006"
    environment:
      AUTH_SERVICE_URL: http://auth-service:3001
      PRODUCTS_SERVICE_URL: http://products-service:3002
      ORDERS_SERVICE_URL: http://orders-service:3003
      PAYMENTS_SERVICE_URL: http://payments-service:3004
      EMAIL_SERVICE_URL: http://email-service:3005
    depends_on:
      - auth-service
      - products-service
      - orders-service
      - payments-service
      - email-service

  # API Gateway routing external traffic to internal services
  api-gateway:
    build: ./packages/api-gateway
    ports:
      - "3000:3000"
    environment:
      REGISTRY_URL: http://service-registry:3006
      NODE_ENV: production
    depends_on:
      - service-registry

  # Authentication service
  auth-service:
    build: ./packages/auth-service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/lemonstand-auth
      JWT_SECRET: supersecretjwt
      JWT_EXPIRES_IN: 90d
      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: example@example.com
      EMAIL_PASSWORD: examplepassword
    depends_on:
      - mongo
      - redis
      - rabbitmq

  # Products service for catalog management
  products-service:
    build: ./packages/products-service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/lemonstand-products
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Orders service for processing and fulfilling orders
  orders-service:
    build: ./packages/orders-service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/lemonstand-orders
      JWT_SECRET: supersecretjwt
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  # Payments service handling Stripe payments
  payments-service:
    build: ./packages/payments-service
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/lemonstand-payments
      JWT_SECRET: supersecretjwt
      STRIPE_SECRET_KEY: sk_test_your_stripe_secret
      STRIPE_WEBHOOK_SECRET: whsec_your_webhook_secret
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  # Email service for asynchronous notifications
  email-service:
    build: ./packages/email-service
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: example@example.com
      SMTP_PASS: examplepassword
    depends_on:
      - rabbitmq

volumes:
  mongo_data:
  redis_data: