apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: lemonstand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3004"
    spec:
      containers:
      - name: payments-service
        image: lemonstand/payments-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: JWT_EXPIRES_IN
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: REDIS_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: RABBITMQ_URL
        - name: REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: REGISTRY_URL
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: lemonstand-secrets
              key: MONGODB_URI
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: lemonstand
spec:
  selector:
    app: payments-service
  ports:
  - port: 3004
    targetPort: 3004
