apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
  namespace: lemonstand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: SERVICE_NAME
        image: IMAGE_NAME
        ports:
        - containerPort: PORT
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: JWT_EXPIRES_IN
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: REDIS_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: lemonstand-config
              key: RABBITMQ_URL
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: lemonstand-secrets
              key: MONGODB_URI
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: PORT
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: PORT
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: lemonstand
spec:
  selector:
    app: SERVICE_NAME
  ports:
  - port: PORT
    targetPort: PORT
